//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------
namespace Presentation.Properties
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.Drawing;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources() { }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("Presentation.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static Bitmap activate_profile => (Bitmap)ResourceManager.GetObject("activate_profile", resourceCulture);
        internal static Bitmap female_icon => (Bitmap)ResourceManager.GetObject("female_icon", resourceCulture);
        internal static Bitmap male_icon => (Bitmap)ResourceManager.GetObject("male_icon", resourceCulture);
        internal static Bitmap person_default_image_female => (Bitmap)ResourceManager.GetObject("person_default_image_female", resourceCulture);
        internal static Bitmap person_default_image_male => (Bitmap)ResourceManager.GetObject("person_default_image_male", resourceCulture);
    }
}